#ifndef AOSTK_BOXLAYOUT_H
#define AOSTK_BOXLAYOUT_H

#include <bits.h>

#define AOSTK_LINES_INNER   BIT0
#define AOSTK_LINES_TOP     BIT1
#define AOSTK_LINES_BOTTOM  BIT2
#define AOSTK_LINES_LEFT    BIT3
#define AOSTK_LINES_RIGHT   BIT4

#endif
